# Generated by Django 3.1.7 on 2021-03-28 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField(default='', max_length=1000)),
                ('content', models.TextField()),
                ('about', models.TextField(default='', max_length=10000)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
