# Generated by Django 3.1.7 on 2021-03-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=50)),
                ('email', models.EmailField(default='Anonymous@gmail.com', max_length=100)),
                ('phone', models.BigIntegerField()),
                ('message', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
